
import React from 'react';

interface Props {
  onAccept: () => void;
}

const DisclaimerModal: React.FC<Props> = ({ onAccept }) => {
  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center bg-black/95 p-4 backdrop-blur-sm">
      <div className="bg-surface border border-surfaceHighlight rounded-xl max-w-md w-full p-6 shadow-2xl">
        <div className="flex flex-col items-center mb-6">
           <div className="w-12 h-12 rounded-full bg-primary/20 flex items-center justify-center mb-4">
               <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-primary"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>
           </div>
           <h2 className="text-xl font-bold text-white text-center">Important Disclaimer</h2>
        </div>
        
        <div className="space-y-4 text-sm text-gray-400 leading-relaxed mb-6 h-64 overflow-y-auto pr-2 custom-scrollbar">
           <p>
             <strong className="text-white">Not Financial Advice:</strong> The content provided by SentientTrader AI is for informational and educational purposes only. It does not constitute financial, investment, or trading advice.
           </p>
           <p>
             <strong className="text-white">AI Limitations:</strong> The signals are generated by Artificial Intelligence (Google Gemini). AI can hallucinate, misinterpret market data, or fail to account for fundamental news events.
           </p>
           <p>
             <strong className="text-white">High Risk Warning:</strong> Cryptocurrency trading, especially on futures/perpetuals, involves extreme risk. You can lose your entire capital. Leverage amplifies both gains and losses.
           </p>
           <p>
              By proceeding, you acknowledge that you are using this tool at your own risk and hold the developers harmless for any trading losses incurred.
           </p>
        </div>

        <button 
          onClick={onAccept}
          className="w-full py-3 bg-primary hover:bg-blue-600 text-white font-bold rounded-lg transition-colors"
        >
          I Understand & Accept Risks
        </button>
      </div>
    </div>
  );
};

export default DisclaimerModal;
